org: avadkk
app: wgs
service: wgs-admin
frameworkVersion: '2'
name: wgs-admin
component: website
stage: dev

inputs:
  src:
    src: ./src
    region: 'ap-northeast-1'
    hook: 'DISABLE_ESLINT_PLUGIN=true npm run build'
    dist: ./build
